template = ""
rev_id = 9
template_sha = "40afa223ab00844a035cff537a1d85d88c975bf8"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "udm"
__UND2C_TRG__ = "hu"
__UNDEFINED_SOURCE__ = "Udmurt"
__UNDEFINED_TARGET__ = "Hungarian"
__UND_SRC__ = "udm"
__UND_TRG__ = "hun"
