template = ""
rev_id = 7
template_sha = "94893e7a5cd0adce3abaa3e278710450dd114995"

[replacements]
__LICENSE__ = ""
__UND2C_SRC__ = "udm"
__UND2C_TRG__ = "hu"
__UNDEFINED_SOURCE__ = "Udmurt"
__UNDEFINED_TARGET__ = "Hungarian"
__UND_SRC__ = "udm"
__UND_TRG__ = "hun"
